### PR TITLE
OC Methods for chunkloader

### PR DESCRIPTION
**Pull request by TxN**
Oops, seems that i've accidentally included merge commits into this pull request. Should i create new?

### CODE REVIEW

**Comment by LemADEC** [comment]
Yes, please make a clean branch with just the chunkloader fixes.

Since we're breaking this code, we might as well fix the API:
- replace active() with enable(), and rename shouldLoad property to isEnabled
- add a getEnergyRequired() method
- remove upgrades() method along with calls to setUpgradeMaxCount() in constructor
- reorder with isEnabled() first, then bounds, radius and finally getEnergyRequired()
Along with:
- rename canLoad property to isActive
- fix clamping of bounds (it's probably bugged on chunkloading and it should be done directly when setting values)
- define common LUA functions, then OC methods, then the CC method

Alternately, you could add proper upgrades handling, for example:
- default radius is 0 (1x1 chunk area), adding a Emerald crystal increases by 1 chunk, up to WarpDriveConfig.CL_MAX_DISTANCE.
- power is reduced by 10% per Superconductor added, up to 5.

**Comment by TxN** [comment]
Done, excluding upgrades part.
Tomorrow i will try to add upgrades handling to chunkloader. Where i can find how to implement it? In Force field block?

**Comment by LemADEC** [comment]
For upgrades:
- in constructor, call setUpgradeMaxCount() for each upgrade type
- when needed, call getUpgradeCount() to adjust behavior
- in the block's onBlockActivated() check BlockEnergyBank, removing the face wrenching part

**Comment by LemADEC** [comment]
Any update on this @TxN ?

**Pull request merged**
