### PR TITLE
Upload zh_CN.lang(for the occasion）

### PR DESCRIPTION
**Pull request by ETStareak**
Because of something,I can't finish it totally now.I will finish it this month.

### CODE REVIEW

**Comment by LemADEC** [comment]
Thanks! I'll add to the next version, soon :)

**Comment by LemADEC** [comment]
I've merged with current structure.
You'll see a few "-tbc" tags where I wasn't sure if it's the proper translation.

**Comment by ETStareak** [comment]
@LemADEC  you have learned Chinese?

**Comment by LemADEC** [comment]
nope, just adding the missing lines :)

**Comment by ETStareak** [comment]
OK，won't be lang.

**Comment by LemADEC** [comment]
What do you mean?

**Comment by LemADEC** [comment]
I've just added the missing keys with their english version for reference.

**Comment by ETStareak** [comment]
hahahahaha，I have made a mistake→_→
“long”,not“lang”
hhhhhhhh

**Comment by LemADEC** [comment]
:)

**Pull request merged**
